### ISSUE TITLE
Py 3.11: AttributeError: module 'inspect' has no attribute 'getargspec'

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.memoize#27]
Running the tests with Plone 6.0 on Python 3.11 fails:

```
File "/Users/maurits/shared-eggs/cp311/plone.memoize-2.1.1-py3.11.egg/plone/memoize/request.rst", line 40, in request.rst
Failed example:
    cached_increment(A(1))
Exception raised:
    Traceback (most recent call last):
      File "/Users/maurits/.pyenv/versions/3.11.0rc2/lib/python3.11/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest request.rst[10]>", line 1, in <module>
        cached_increment(A(1))
      File "/Users/maurits/shared-eggs/cp311/plone.memoize-2.1.1-py3.11.egg/plone/memoize/volatile.py", line 71, in replacement
        cache = get_cache(fun, *args, **kwargs)
      File "/Users/maurits/shared-eggs/cp311/plone.memoize-2.1.1-py3.11.egg/plone/memoize/request.py", line 56, in _store_in_annotation
        spec = inspect.getargspec(fun)
    AttributeError: module 'inspect' has no attribute 'getargspec'
```

**Comment by jugmac00** [comment]
https://docs.python.org/3/library/inspect.html#inspect.getargspec
